<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "absent".
 *
 * @property integer $id
 * @property integer $absent
 * @property integer $reason
 * @property string $date
 * @property integer $subject_id
 * @property integer $student_id
 *
 * @property \app\models\Student $student
 * @property \app\models\Subject $subject
 * @property string $aliasModel
 */
abstract class Absent extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'absent';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['absent', 'reason', 'subject_id', 'student_id'], 'integer'],
            [['date', 'subject_id', 'student_id'], 'required'],
            [['date'], 'safe'],
            [['student_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Student::className(), 'targetAttribute' => ['student_id' => 'id']],
            [['subject_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Subject::className(), 'targetAttribute' => ['subject_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'absent' => Yii::t('models', 'Absent'),
            'reason' => Yii::t('models', 'Reason'),
            'date' => Yii::t('models', 'Date'),
            'subject_id' => Yii::t('models', 'Subject ID'),
            'student_id' => Yii::t('models', 'Student ID'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getStudent()
    {
        return $this->hasOne(\app\models\Student::className(), ['id' => 'student_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSubject()
    {
        return $this->hasOne(\app\models\Subject::className(), ['id' => 'subject_id']);
    }




}
