<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "activity".
 *
 * @property integer $id
 * @property integer $subject_id
 * @property integer $student_id
 * @property integer $type_activity_id
 *
 * @property \app\models\Student $student
 * @property \app\models\Subject $subject
 * @property \app\models\TypeActivity $typeActivity
 * @property string $aliasModel
 */
abstract class Activity extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'activity';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['subject_id', 'student_id', 'type_activity_id'], 'required'],
            [['subject_id', 'student_id', 'type_activity_id'], 'integer'],
            [['student_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Student::className(), 'targetAttribute' => ['student_id' => 'id']],
            [['subject_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Subject::className(), 'targetAttribute' => ['subject_id' => 'id']],
            [['type_activity_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\TypeActivity::className(), 'targetAttribute' => ['type_activity_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'subject_id' => Yii::t('models', 'Subject ID'),
            'student_id' => Yii::t('models', 'Student ID'),
            'type_activity_id' => Yii::t('models', 'Type Activity ID'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getStudent()
    {
        return $this->hasOne(\app\models\Student::className(), ['id' => 'student_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSubject()
    {
        return $this->hasOne(\app\models\Subject::className(), ['id' => 'subject_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTypeActivity()
    {
        return $this->hasOne(\app\models\TypeActivity::className(), ['id' => 'type_activity_id']);
    }




}
