<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "answer".
 *
 * @property integer $id
 * @property string $answer
 * @property integer $answer_true
 * @property integer $question_id
 *
 * @property \app\models\Question $question
 * @property \app\models\StudentAnswer[] $studentAnswers
 * @property string $aliasModel
 */
abstract class Answer extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'answer';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['answer', 'question_id'], 'required'],
            [['answer'], 'string'],
            [['answer_true', 'question_id'], 'integer'],
            [['question_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Question::className(), 'targetAttribute' => ['question_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'answer' => Yii::t('models', 'Answer'),
            'answer_true' => Yii::t('models', 'Answer True'),
            'question_id' => Yii::t('models', 'Question ID'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getQuestion()
    {
        return $this->hasOne(\app\models\Question::className(), ['id' => 'question_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getStudentAnswers()
    {
        return $this->hasMany(\app\models\StudentAnswer::className(), ['answer_id' => 'id']);
    }




}
