<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "class_room".
 *
 * @property integer $id
 * @property string $class_room_name
 *
 * @property \app\models\StudentHasClassRoom[] $studentHasClassRooms
 * @property \app\models\Student[] $students
 * @property \app\models\Subject[] $subjects
 * @property string $aliasModel
 */
abstract class ClassRoom extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'class_room';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['class_room_name'], 'required'],
            [['class_room_name'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'class_room_name' => Yii::t('models', 'Class Room Name'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getStudentHasClassRooms()
    {
        return $this->hasMany(\app\models\StudentHasClassRoom::className(), ['class_room_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getStudents()
    {
        return $this->hasMany(\app\models\Student::className(), ['id' => 'student_id'])->viaTable('student_has_class_room', ['class_room_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSubjects()
    {
        return $this->hasMany(\app\models\Subject::className(), ['class_room_id' => 'id']);
    }




}
