<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "student_has_class_room".
 *
 * @property integer $student_id
 * @property integer $class_room_id
 *
 * @property \app\models\ClassRoom $classRoom
 * @property \app\models\Student $student
 * @property string $aliasModel
 */
abstract class StudentHasClassRoom extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'student_has_class_room';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['student_id', 'class_room_id'], 'required'],
            [['student_id', 'class_room_id'], 'integer'],
            [['student_id', 'class_room_id'], 'unique', 'targetAttribute' => ['student_id', 'class_room_id']],
            [['class_room_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\ClassRoom::className(), 'targetAttribute' => ['class_room_id' => 'id']],
            [['student_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Student::className(), 'targetAttribute' => ['student_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'student_id' => Yii::t('models', 'Student ID'),
            'class_room_id' => Yii::t('models', 'Class Room ID'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getClassRoom()
    {
        return $this->hasOne(\app\models\ClassRoom::className(), ['id' => 'class_room_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getStudent()
    {
        return $this->hasOne(\app\models\Student::className(), ['id' => 'student_id']);
    }




}
