<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "student".
 *
 * @property integer $id
 * @property string $student_code
 * @property string $first_name
 * @property string $last_name
 *
 * @property \app\models\ClassRoom[] $classRooms
 * @property \app\models\StudentAnswer[] $studentAnswers
 * @property \app\models\StudentHasClassRoom[] $studentHasClassRooms
 * @property string $aliasModel
 */
abstract class Student extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'student';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['student_code', 'first_name', 'last_name'], 'required'],
            [['student_code', 'first_name'], 'string', 'max' => 255],
            [['last_name'], 'string', 'max' => 45]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'student_code' => Yii::t('models', 'Student Code'),
            'first_name' => Yii::t('models', 'First Name'),
            'last_name' => Yii::t('models', 'Last Name'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getClassRooms()
    {
        return $this->hasMany(\app\models\ClassRoom::className(), ['id' => 'class_room_id'])->viaTable('student_has_class_room', ['student_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getStudentAnswers()
    {
        return $this->hasMany(\app\models\StudentAnswer::className(), ['student_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getStudentHasClassRooms()
    {
        return $this->hasMany(\app\models\StudentHasClassRoom::className(), ['student_id' => 'id']);
    }




}
